---
title: "LV_Discharge"
output: html_document
date: "2024-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in hydrology data
```{r}
# load libraries
library(dplyr)
library(dataRetrieval)
library(lubridate)
library(tidyr)
library(ggplot2)
library(viridis)
library(readxl)
library(imputeTS)
library(tsibble)

# Get data for LV
lv_no <- '401733105392404'

## get data for ice windows
# full ice to functional ice window
full_to_func <- read_xlsx("Output_Files/20240829_DischargeSlope_FullFunctional.xlsx")
# full ice to no ice
full_to_no <- read_xlsx("Output_Files/20240829_DischargeSlope_FullNo.xlsx")
# functional to no
func_to_no <- read_xlsx("Output_Files/20240829_DischargeSlope_FunctionalNo.xlsx")
## test for indexing
#testtest <- full_to_func[3, "slope_cfs_per_day"]

# define parameters of interest, and get those parameter names
params <- c('00060', '00671', '80154', '00665')

# get daily values from NWIS
lv_dat <- readNWISdv(siteNumbers = lv_no, parameterCd = params,
                         startDate = '1983-10-01', endDate = '2024-09-30')

# rename columns using renameNWISColumns from package dataRetrieval
lv_dat <- renameNWISColumns(lv_dat,
                                p00665 = "TP_mgL",
                                p00671 = "Orthophosphate_mgL",
                                p80154 = "SS_mgL")


# repeating process for 2019 to 2022
# lv_dat19_22 <- readNWISdv(siteNumbers = lv_no, parameterCd = params,
#                          startDate = '2019-10-01', endDate = '2022-09-30')
# rename columns using renameNWISColumns from package dataRetrieval
# lv_dat19_22 <- renameNWISColumns(lv_dat19_22,
#                                 p00665 = "TP_mgL",
#                                 p00671 = "Orthophosphate_mgL",
#                                 p80154 = "SS_mgL")
```

# Read in temp and cond data
```{r}

#What data are available?
dailyDataAvailable <- whatNWISdata(
  siteNumber = lv_no
)

#Pull in temperature and conductivity Loch outlet
parameterCd <- c('00095','00010')
lv_dat_outlet_input <- readWQPqw(paste0("USGS-", lv_no), parameterCd)


#Clean up dataframe
lv_dat_outlet <- lv_dat_outlet_input %>%
  select(ActivityStartDate, ActivityConductingOrganizationText, CharacteristicName, ResultMeasureValue) %>%
  pivot_wider(names_from = CharacteristicName, values_from = ResultMeasureValue, values_fn = mean) %>%
  rename(cond_uScm="Specific conductance",
         temperature_C_raw="Temperature, water",
         Date = "ActivityStartDate") %>%
  select(-ActivityConductingOrganizationText) %>%
  mutate(wy_doy = hydro.day(Date)) %>%
  addWaterYear() %>% 
  distinct(Date, .keep_all = TRUE) %>%
  as_tsibble(., key = waterYear, index = Date) %>% #time series tibble
  fill_gaps() %>%  #makes the missing data implicit
  mutate(cond_uScm_impute = imputeTS::na_interpolation(cond_uScm, maxgap = 7),
         temperature_C_raw_impute = imputeTS::na_interpolation(temperature_C_raw, maxgap = 7))


```


```{r}
# use function `grep` to identify which columns are code columns
lv_names <- names(lv_dat)
grep('_cd', lv_names) # returns the index of the match

# 2019-2022
# use function `grep` to identify which columns are code columns
# lv_names19_22 <- names(lv_dat19_22)
# grep('_cd', lv_names19_22) # returns the index of the match

```


```{r}
grep('_cd', lv_names, value = TRUE) # returns the matched elements themselves
```


```{r}
# change the code column names to be more explicit about what they contain
# using function gsub
gsub('_cd', '_code', lv_names)

# gsub('_cd', '_code', lv_names19_22)
```


```{r}
lv_dat <- select(lv_dat, -contains('_cd'))
head(lv_dat)


# lv_dat19_22 <- select(lv_dat19_22, -contains('_cd'))
# head(lv_dat19_22)
```


```{r}
# add water year variable "waterYear" to our dataframe
lv_dat <- addWaterYear(lv_dat)

# calculate cumulative discharge for each year by first grouping by water year,
# and then using the "cumsum" function. Add day of water year for plotting purposes.
# These steps will build a new dataframe, with the existing information in yahara_dat
# but with two additional columns.
cumulative_dat <- group_by(lv_dat, waterYear) %>%
  mutate(cumulative_dis = cumsum(Flow), 
         wy_doy = seq(1:n()))

# ungroup cumulative_dat 
cumulative_dat_ungroup <- cumulative_dat %>%
  ungroup() %>%
  as.data.frame()

# scaling across 2013 onwards
test <- cumulative_dat_ungroup %>%
  filter(waterYear>=2013) %>%
  group_by(waterYear) %>% 
  mutate(cumulative_dis_z = scale(cumulative_dis))


# visually compare cumulative discharge across years
ggplot(cumulative_dat, aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_line(aes(color = waterYear)) +
  scale_color_viridis_c() +
  scale_x_continuous(breaks = c(1, 93, 184, 275), labels = c("Oct 1", "Jan 1", "Apr 1", "July 1")) +
  theme_bw() +
  labs(color = "Water Year", x = "", y = "Cumulative Discharge")

```

```{r}

```



```{r}

# Water Year 2012:

# plot ungrouped data frame
ggplot(cumulative_dat_ungroup %>%
         filter(waterYear == 2012) %>%
         mutate(waterYear=as.factor(waterYear)), aes(x = wy_doy, y = cumulative_dis, group = waterYear))+
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(0, 366), y = c(0, 500)) +
  labs(color = "Water Year 2012", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(waterYear~.)+
  geom_vline(xintercept=208, color="red") 

```

```{r}
# water year 2013
ggplot(cumulative_dat_ungroup %>%
         filter(waterYear == 2013) %>%
         mutate(waterYear=as.factor(waterYear)), aes(x = wy_doy, y = cumulative_dis, group = waterYear))+
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(200, 250), y = c(0, 500)) +
  labs(color = "Water Year 2013", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(waterYear~.)+
  geom_vline(xintercept=241, color="red") 
```


```{r}
# messing around with the dfs

# joining the three "windows" dfs together
# bind_rows(dataframe1, dataframe2, dataframe3) - need same headers
slopes_and_intercepts <- bind_rows(full_to_func, full_to_no, func_to_no)

# creating new columns to separate lakeID and water year, making slope and intercept num instead of char
slopes_and_intercepts_sep <- slopes_and_intercepts %>% 
  separate(Lake_WaterYear, into = c("Lake_ID", "waterYear"), sep = "_", remove = FALSE) %>% mutate(waterYear=as.numeric(waterYear), slope_cfs_per_day=as.numeric(slope_cfs_per_day), intercept = as.numeric(intercept))

# joining slope df with all of the windows slope dfs
test_big_join <- cumulative_dat_ungroup %>% left_join(.,slopes_and_intercepts_sep, by="waterYear")

# filtering out a water year within the joined df
test2a <-test_big_join %>%
    filter(waterYear == 2014)

# how to add the abline if all the "windows" dfs with slopes were joined with cumulativeQ df:
  geom_abline(test %>% filter(window="the window i want") ,aes(intercept = intercept,
                  slope = slope_cfs_per_day),
              color = "orange")
  
# how it was working only using test (only one window joined)
  geom_abline(aes(intercept = intercept,
                  slope = slope_cfs_per_day),
              color = "orange")
  
# running a simple regression to check the slope in the slopes df:
  test2014 <- cumulative_dat_ungroup %>% 
  filter(Date>="2014-04-21"&Date<="2014-05-05")

  lm2014 <- lm(cumulative_dis~wy_doy, data = test2014)
  summary(lm2014)

```


```{r fig.width=14}
# water year 2014

# this plot is using the "test" df which is joined with the full_to_func df
ggplot(
  test_big_join %>%
    filter(waterYear == 2014) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=205,xmax=247,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2014) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(180, 260), y = c(100, 750)) +
  labs(color = "Water Year 2014", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  geom_vline(xintercept = 219, color = "cornflowerblue")+
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))



# export all plots
# check the structure!

```


```{r fig.width=14}
# water year 2015
# this plot is using the "test" df which is joined with the full_to_func df
ggplot(
  test_big_join %>%
    filter(waterYear == 2015) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=197,xmax=239,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2015) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 220, color = "cornflowerblue", size = 1)+
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(180, 260), y = c(130, 500)) +
  labs(color = "Water Year 2015", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2016
ggplot(
  test_big_join %>%
    filter(waterYear == 2016) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=195,xmax=251,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2016) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 237, color = "cornflowerblue")+
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(180, 260), y = c(50, 700)) +
  labs(color = "Water Year 2016", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2017
ggplot(
  test_big_join %>%
    filter(waterYear == 2017) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=173,xmax=243,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2017) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 229, color = "cornflowerblue")+ # functional ice off
  geom_vline(xintercept = 238, color = "orange")+ # pierson ice off
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(170, 255), y = c(50, 600)) +
  labs(color = "Water Year 2017", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width =14}
# water year 2018
ggplot(
  test_big_join %>%
    filter(waterYear == 2018) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=214,xmax=235,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2018) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 221, color = "cornflowerblue")+ # functional ice off
  geom_vline(xintercept = 229, color = "orange")+ # pierson ice off
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(210, 240), y = c(180, 750)) +
  labs(color = "Water Year 2018", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2019
ggplot(
  test_big_join %>%
    filter(waterYear == 2019) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=206,xmax=260,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2019) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 242, color = "cornflowerblue")+ # functional ice off
  geom_vline(xintercept = 253, color = "orange")+ # pierson ice off
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(200, 270), y = c(180, 1000)) +
  labs(color = "Water Year 2019", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2020
ggplot(
  test_big_join %>%
    filter(waterYear == 2020) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=211,xmax=234,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2020) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 218, color = "cornflowerblue")+ # functional ice off
  #geom_vline(xintercept = 253, color = "orange")+ # pierson ice off - missing for this year
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(200, 240), y = c(50, 350)) +
  labs(color = "Water Year 2020", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2021
ggplot(
  test_big_join %>%
    filter(waterYear == 2021) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=210,xmax=255,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2021) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 238, color = "cornflowerblue")+ # functional ice off
  geom_vline(xintercept = 250, color = "orange", size = .9)+ # pierson ice off
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(200, 270), y = c(50, 900)) +
  labs(color = "Water Year 2021", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2022
ggplot(
  test_big_join %>%
    filter(waterYear == 2022) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=216,xmax=244,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2022) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 230, color = "cornflowerblue", size = 0.9)+ # functional ice off
  #geom_vline(xintercept = 250, color = "orange", size = 0.9)+ # pierson ice off - missing for this year
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(200, 250), y = c(50, 450)) +
  labs(color = "Water Year 2022", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))
```


```{r fig.width=14}
# water year 2023
ggplot(
  test_big_join %>%
    filter(waterYear == 2023) %>%
    mutate(waterYear = as.factor(waterYear)),
  aes(x = wy_doy, y = cumulative_dis, group = waterYear)) +
  geom_rect(aes(xmin=215,xmax=243,ymin=-Inf,ymax=Inf), fill="grey",alpha=0.01)+
  geom_abline(data = test_big_join %>% filter(waterYear == 2023) ,aes(intercept = intercept, slope = slope_cfs_per_day,color = Window)) +
  geom_vline(xintercept = 229, color = "cornflowerblue")+ # functional ice off
  #geom_vline(xintercept = 250, color = "orange", size = 0.9)+ # pierson ice off - missing for this year
  geom_line(aes(color = waterYear)) +
  theme_bw() +
  lims(x = c(205, 250), y = c(70, 600)) +
  labs(color = "Water Year 2023", x = "Water Year DOY", y = "Cumulative Discharge") +
  facet_wrap(Window ~ .) +
  theme(panel.ontop=TRUE, panel.background = element_rect(fill = NA))


# saving this simple plot just in case

# ggplot(cumulative_dat_ungroup %>%
#          filter(waterYear == 2023) %>%
#          mutate(waterYear=as.factor(waterYear)), aes(x = wy_doy, y = cumulative_dis, group = waterYear))+
#   geom_line(aes(color = waterYear)) +
#   theme_bw() +
#   lims(x = c(200, 250), y = c(0, 500)) +
#   labs(color = "Water Year 2023", x = "Water Year DOY", y = "Cumulative Discharge") +
#   facet_wrap(waterYear~.)+
#   geom_vline(xintercept=229, color="red")
```


```{r}
# joining ice off table with discharge table
ice_off_dates <- read.csv("ice_off_dates.csv")

cumulative_dat_iceoff <- merge(x=cumulative_dat, y=ice_off_dates, by=c("waterYear","wy_doy"), all.x=T)
```


```{r}

```


